name: Run DataSave_forMac.app on Excel

on: [push]

jobs:
  run-datasave:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Excel
      run: brew install --cask microsoft-excel

    - name: Grant execute permissions for DataSave_forMac.app
      run: chmod +x ./DataSave_forMac.app/Contents/MacOS/DataSave_forMac

    - name: Run DataSave_forMac.app
      run: |
        ./DataSave_forMac.app/Contents/MacOS/DataSave_forMac --args "test.xlsx"
