name: Build JXA Application2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create application file
      run: |
        # スクリプトの場所に移動
        cd $GITHUB_WORKSPACE/xl2tx

        # 必要なディレクトリを作成
        mkdir -p output

        # osacompileコマンドを使用してアプリケーションに変換
        osacompile -o output/SampleApp.app sample.js

    - name: Archive application
      run: |
        # アプリケーションをZIP形式に圧縮
        cd $GITHUB_WORKSPACE/xl2tx/output
        zip -r SampleApp.zip SampleApp.app

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SampleApp
        path: xl2tx/output/SampleApp.zip
