name: Build JXA Application2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create application file
      run: |
        # スクリプトの場所に移動
        cd $GITHUB_WORKSPACE/

        # 必要なディレクトリを作成
        mkdir -p output

        # osacompileコマンドを使用してアプリケーションに変換
        osacompile -o output/SampleApp3.app sample3.js

    - name: Archive application
      run: |
        # アプリケーションをZIP形式に圧縮
        cd $GITHUB_WORKSPACE/output
        zip -r SampleApp3.zip SampleApp3.app

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SampleApp3
        path: $GITHUB_WORKSPACE/output/SampleApp3.zip
